apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-worker
  template:
    metadata:
      labels:
        app: python-worker
    spec:
      containers:
      - name: python-worker
        image: python-worker:latest
        imagePullPolicy: IfNotPresent